theme: jekyll-theme-slate
title: My Projects Portfolio
description: My projects on various Data Science skills!
navbar-links:
  About Me: "aboutme"
navbar-col: "#EAEAEA"
social-network-links:
  email: "karan433155@gmail.com"
